### PR TITLE
10343 - New EU flag available in SwrveConfig

### PR DESCRIPTION
**Pull request by shanethmoore**
Developers can now choose to send events to EU stack for latency benefits or data laws

### CODE REVIEW

**Comment by shanethmoore** [comment]
@Sergio-Mira Has 3.5 been released? Should I make a 3.5.1?

**Comment by Sergio-Mira** [comment]
3.5 is the next version :dancer:

**Comment by shanethmoore** [comment]
@Sergio-Mira Updated to Enum flags.

**Comment by Sergio-Mira** [comment]
:rocket: !

**Pull request merged**
